#!/bin/bash
# Print Perseverance image URLs from a given Sol date
# For example, to print URLs of images from Sol 123, use:
# p_urls 123

if [ -z "$1" ]
then
    echo "Print Perseverance image URLs from a given Sol date"
    echo "For example, to print URLs of images from Sol 123, use:"
    echo "$0 123"
else

n=`curl --no-progress-meter  "https://mars.nasa.gov/rss/api/?feed=raw_images&category=mars2020,ingenuity&feedtype=json&ver=1.2&num=10&page=0&=&=&=&=&=&order=sol%20desc&condition_2=$1:sol:gte&condition_3=$1:sol:lte" | python3 -c "import json,sys;obj=json.load(sys.stdin);print(obj['total_results']);"`

p=0

while [ $(( $p * 100 )) -lt $n ]
do
  curl --no-progress-meter "https://mars.nasa.gov/rss/api/?feed=raw_images&category=mars2020,ingenuity&feedtype=json&ver=1.2&num=100&page=$p&=&=&=&=&=&order=sol%20desc&condition_2=$1:sol:gte&condition_3=$1:sol:lte" | python3 -c "import json,sys;obj=json.load(sys.stdin);[print(x['image_files']['full_res']) for x in obj['images']];"
  p=$(( $p + 1 ))
done
echo "Total: $n"

fi


